spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mariadb://trinitydb.cpyoritr64dk.ap-northeast-2.rds.amazonaws.com:3306/TrinityDB
    username: root
    password: mint1234
    driver-class-name: org.mariadb.jdbc.Driver
