version: '3'

services:
  elastic:
    container_name: elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.2
    volumes:
      - ./elastic:/usr/share/elasticsearch/data:z
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: -Xms1g -Xmx1g
      # ELASTIC PASSWORD INPUT
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
      # SINGLE-NODE MODE
      discovery.type: single-node
  
  # kibana:
  #   container_name: kibana
  #   image: docker.elastic.co/kibana/kibana:8.2.2
  #   depends_on:
  #     - elastic
  #   build: ./kibana
  #   ports:
  #     - "5601:5601"
  #   environment:
  #     KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD:-}

  # logstash:
  #   container_name: logstash
  #   image: docker.elastic.co/logstash/logstash:8.2.2
  #   depends_on:
  #     - elastic
  #   build: ./logstash
  #   volumes:
        # Volume for Accessing files in docker from outside docker
  #     - ./logstash/pipeline:/usr/share/logstash/pipeline:ro,Z
  #   ports:
  #     - "5044:5044"
  #     - "5000:5000/tcp"
  #     - "5000:5000/udp"
  #     - "9600:9600"
  #   environment:
  #     LS_JAVA_OPTS: -Xms1g -Xmx1g
  #     LOGSTASH_INTERNAL_PASSWORD: ${LOGSTASH_INTERNAL_PASSWORD:-}
  
# networks:
#   elk_network:
#     driver: bridge